# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 91154d6a62cec193a0b20b72003d05782bbb660794b34ae3382d523f197c255c4371965e8023fb40d868f4259140643c6935bc49e57755e4d27ac780d33054d4

test:
  secret_key_base: 4187be51fd3e2104bf84384c3536513bbacad255907bb07d2a6f04df1ed5e476f3172682bd5ea42a7ca0be79c40f686192c2b2dcaa17ea934076212b1411e366

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
